__By: Paula Alvarez, Victor Camero, Daniela Lavanderas, Fernanda Vásquez__

# Analyze

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
import seaborn as sns

In [2]:
filter_dataset = pd.read_csv("../data/filtered_data_elpino.csv", delimiter=';')
filter_dataset.head(3)

,Diag 01 Principal (cod+des),Diag 02 Secundario (cod+des),Diag 03 Secundario (cod+des),Diag 04 Secundario (cod+des),Diag 05 Secundario (cod+des),Diag 06 Secundario (cod+des),Diag 07 Secundario (cod+des),Diag 08 Secundario (cod+des),Diag 09 Secundario (cod+des),Diag 10 Secundario (cod+des),...,Proced 24 Secundario (cod+des),Proced 25 Secundario (cod+des),Proced 26 Secundario (cod+des),Proced 27 Secundario (cod+des),Proced 28 Secundario (cod+des),Proced 29 Secundario (cod+des),Proced 30 Secundario (cod+des),Edad en años,Sexo (Desc),GRD
0,A41.8 - Otras septicemias especificadas,B37.6 - Endocarditis debida a candida (I39.8*),"I39.8 - Endocarditis, válvula no especificada,...",N10 - Nefritis tubulointersticial aguda,B96.1 - Klebsiella pneumoniae [K. pneumoniae] ...,L89.9 - Úlcera de decúbito y area de presión n...,L08.9 - Infección local de la piel y del tejid...,B96.2 - Escherichia coli [E. coli] como causa ...,A41.5 - Sepsis por otros organnismos Gram nega...,J86.9 - Piotórax sin fístula,...,99.84 - AISLAMIENTO,88.72 - ECOCARDIOGRAFIA,90.42 - EXAMEN MICROSCOPICO RESPIRATORIO.CULTIVO,90.52 - EXAMEN MICROSCOPICO SANGRE.CULTIVO,91.39 - EXAMEN MICROSCOPICO URINARIO INFERIOR....,91.33 - EXAMEN MICROSCOPICO URINARIO INFERIOR....,87.03 - TOMOGRAFIA AXIAL COMPUTERIZADA CABEZA,40,Hombre,184103 - MH SEPTICEMIA W/MCC
1,"U07.1 - COVID-19, virus identificado",J12.8 - Neumonía debida a otros virus,R06.0 - Disnea,R05 - Tos,"R50.9 - Fiebre, no especificada",Z29.0 - Aislamiento,Z01.7 - Examen de laboratorio,"J96.00 - Insuficiencia respiratoria aguda, Tip...",J94.2 - Hemotórax,J92.9 - Paquipleuritis sin asbestosis,...,91.62 - EXAMEN MICROSCOPICO PIEL.CULTIVO,90.43 - EXAMEN MICROSCOPICO RESPIRATORIO.CULTI...,91.39 - EXAMEN MICROSCOPICO URINARIO INFERIOR....,90.52 - EXAMEN MICROSCOPICO SANGRE.CULTIVO,91.32 - EXAMEN MICROSCOPICO URINARIO INFERIOR....,96.59 - IRRIGACION HERIDA OTRA,90.99 - EXAMEN MICROSCOPICO DIGESTIVO INFERIOR...,53,Hombre,041013 - PH ECMO VENTILACIÓN MECÁNICA PROLONGA...
2,K56.5 - Adherencias [bridas] intestinales con ...,R57.2 - Shock séptico,R57.1 - Choque hipovolémico,J80 - Síndrome de dificultad respiratoria del ...,Y95 - Afección nosocomial,J15.0 - Neumonía debida a Klebsiella pneumoniae,U82.2 - Resistencia a Betalactamasas de amplio...,B95.6 - Staphylococcus aureus como causa de en...,B96.8 - Otros agentes bacterianos especificado...,B37.1 - Candidiasis pulmonar,...,99.84 - AISLAMIENTO,91.73 - EXAMEN MICROSCOPICO HERIDA OPERATORIA....,90.53 - EXAMEN MICROSCOPICO SANGRE.CULTIVO Y S...,99.26 - INYECCION TRANQUILIZANTE,89.39 - OTRAS MEDICIONES Y EXAMENES NO QUIRURG...,89.66 - GASOMETRIA VENA,89.65 - GASOMETRIA ARTERIA,65,Hombre,041013 - PH ECMO VENTILACIÓN MECÁNICA PROLONGA...

In [3]:
filter_dataset.shape

(14279, 68)

In [4]:
umbral = int(0.90 * filter_dataset.shape[0])  
# Eliminar columnas con menos de "umbral" valores no nulos
clean_data = filter_dataset.dropna(axis=1, thresh=umbral)
clean_data.head()

,Diag 01 Principal (cod+des),Diag 02 Secundario (cod+des),Proced 01 Principal (cod+des),Proced 02 Secundario (cod+des),Proced 03 Secundario (cod+des),Proced 04 Secundario (cod+des),Proced 05 Secundario (cod+des),Edad en años,Sexo (Desc),GRD
0,A41.8 - Otras septicemias especificadas,B37.6 - Endocarditis debida a candida (I39.8*),"86.28 - DESBRIDAMIENTO HERIDA,INFECCION O QUEM...",34.91 - TORACOCENTESIS,88.38 - TOMOGRAFIA AXIAL COMPUTERIZADA OTRA,87.41 - TOMOGRAFIA AXIAL COMPUTERIZADA TORAX,88.75 - ECOGRAFIA APARATO URINARIO,40,Hombre,184103 - MH SEPTICEMIA W/MCC
1,"U07.1 - COVID-19, virus identificado",J12.8 - Neumonía debida a otros virus,31.1 - TRAQUEOSTOMIA TEMPORAL,"86.28 - DESBRIDAMIENTO HERIDA,INFECCION O QUEM...",96.72 - VENTILACION MECANICA CONTINUA OTRA.DUR...,93.90 - RESPIRACION PRESION POSITIVA CONTINUA ...,89.7 - EXAMEN FISICO GENERAL,53,Hombre,041013 - PH ECMO VENTILACIÓN MECÁNICA PROLONGA...
2,K56.5 - Adherencias [bridas] intestinales con ...,R57.2 - Shock séptico,"86.22 - DESBRIDAMIENTO HERIDA,INFECCION O QUEM...",54.59 - LISIS ADHERENCIA PERITONEO.OTRA,96.72 - VENTILACION MECANICA CONTINUA OTRA.DUR...,31.1 - TRAQUEOSTOMIA TEMPORAL,45.13 - ESOFAGOGASTRODUODENOSCOPIA [EGD],65,Hombre,041013 - PH ECMO VENTILACIÓN MECÁNICA PROLONGA...
3,K76.8 - Otras enfermedades especificadas del h...,K66.1 - Hemoperitoneo,54.19 - LAPAROTOMIA.OTRA,39.98 - CONTROL HEMORRAGIA NEOM,"86.28 - DESBRIDAMIENTO HERIDA,INFECCION O QUEM...",54.62 - CIERRE DIFERIDO HERIDA ABDOMEN EN GRAN...,96.72 - VENTILACION MECANICA CONTINUA OTRA.DUR...,61,Hombre,041023 - PH VENTILACIÓN MECÁNICA PROLONGADA SI...
4,T81.0 - Hemorragia y hematoma que complican un...,"Y83.2 - Operación quirúrgica con anastomosis, ...",54.11 - LAPAROTOMIA EXPLORATORIA,45.90 - ANASTOMOSIS INTESTINO.NEOM,46.73 - SUTURA INTESTINO DELGADO SALVO DUODENO,46.20 - ILEOSTOMIA.NEOM,"86.28 - DESBRIDAMIENTO HERIDA,INFECCION O QUEM...",30,Hombre,041023 - PH VENTILACIÓN MECÁNICA PROLONGADA SI...

In [5]:
clean_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14279 entries, 0 to 14278
Data columns (total 10 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Diag 01 Principal (cod+des)     14279 non-null  object
 1   Diag 02 Secundario (cod+des)    13084 non-null  object
 2   Proced 01 Principal (cod+des)   14279 non-null  object
 3   Proced 02 Secundario (cod+des)  14147 non-null  object
 4   Proced 03 Secundario (cod+des)  13942 non-null  object
 5   Proced 04 Secundario (cod+des)  13685 non-null  object
 6   Proced 05 Secundario (cod+des)  13333 non-null  object
 7   Edad en años                    14279 non-null  int64
 8   Sexo (Desc)                     14279 non-null  object
 9   GRD                             14279 non-null  object
dtypes: int64(1), object(9)
memory usage: 1.1+ MB

In [6]:
clean_data.shape

(14279, 10)

In [7]:
clean_data.isnull().sum()

Diag 01 Principal (cod+des)          0
Diag 02 Secundario (cod+des)      1195
Proced 01 Principal (cod+des)        0
Proced 02 Secundario (cod+des)     132
Proced 03 Secundario (cod+des)     337
Proced 04 Secundario (cod+des)     594
Proced 05 Secundario (cod+des)     946
Edad en años                         0
Sexo (Desc)                          0
GRD                                  0
dtype: int64

In [ ]:
clean_data