In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
import warnings
warnings.filterwarnings('ignore')

In [3]:
# Cargar el dataset
print("Cargando el dataset...")
df = pd.read_csv('withingLastNumberGRD.csv', delimiter=';')

# Mostrar las primeras filas del dataset
df.head()

Cargando el dataset...

,Diag 01 Principal (cod+des),Diag 02 Secundario (cod+des),Diag 03 Secundario (cod+des),Diag 04 Secundario (cod+des),Diag 05 Secundario (cod+des),Diag 06 Secundario (cod+des),Diag 07 Secundario (cod+des),Diag 08 Secundario (cod+des),Diag 09 Secundario (cod+des),Diag 10 Secundario (cod+des),...,Proced 24 Secundario (cod+des),Proced 25 Secundario (cod+des),Proced 26 Secundario (cod+des),Proced 27 Secundario (cod+des),Proced 28 Secundario (cod+des),Proced 29 Secundario (cod+des),Proced 30 Secundario (cod+des),Edad en años,Sexo (Desc),GRD
0,A41.8,B37.6,I39.8,N10,B96.1,L89.9,L08.9,B96.2,A41.5,J86.9,...,99.84,88.72,90.42,90.52,91.39,91.33,87.03,40,1,18410
1,U07.1,J12.8,R06.0,R05,R50.9,Z29.0,Z01.7,J96.00,J94.2,J92.9,...,91.62,90.43,91.39,90.52,91.32,96.59,90.99,53,1,4101
2,K56.5,R57.2,R57.1,J80,Y95,J15.0,U82.2,B95.6,B96.8,B37.1,...,99.84,91.73,90.53,99.26,89.39,89.66,89.65,65,1,4101
3,K76.8,K66.1,N18.5,D64.9,E87.5,E87.2,J81,N17.8,J44.9,R41.0,...,57.94,0.13,0.17,99.04,99.18,99.21,99.23,61,1,4102
4,T81.0,Y83.2,S31.1,S36.80,W31.62,J96.09,J15.0,U82.2,U07.1,N39.0,...,90.52,91.39,91.32,93.90,99.15,96.59,45.13,30,1,4102

In [4]:
# Información básica del dataset
print("Información del dataset:")
df.info()

# Estadísticas descriptivas
print("\nEstadísticas descriptivas:")
df.describe()

Información del dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14279 entries, 0 to 14278
Data columns (total 68 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Diag 01 Principal (cod+des)     14279 non-null  object
 1   Diag 02 Secundario (cod+des)    14279 non-null  object
 2   Diag 03 Secundario (cod+des)    14279 non-null  object
 3   Diag 04 Secundario (cod+des)    14279 non-null  object
 4   Diag 05 Secundario (cod+des)    14279 non-null  object
 5   Diag 06 Secundario (cod+des)    14279 non-null  object
 6   Diag 07 Secundario (cod+des)    14279 non-null  object
 7   Diag 08 Secundario (cod+des)    14279 non-null  object
 8   Diag 09 Secundario (cod+des)    14279 non-null  object
 9   Diag 10 Secundario (cod+des)    14279 non-null  object
 10  Diag 11 Secundario (cod+des)    14279 non-null  object
 11  Diag 12 Secundario (cod+des)    14279 non-null  object
 12  Diag 13 Secundario (cod+des)    14279 non-null  object
 13  Diag 14 Secundario (cod+des)    14279 non-null  object
 14  Diag 15 Secundario (cod+des)    14279 non-null  object
 15  Diag 16 Secundario (cod+des)    14279 non-null  object
 16  Diag 17 Secundario (cod+des)    14279 non-null  object
 17  Diag 18 Secundario (cod+des)    14279 non-null  object
 18  Diag 19 Secundario (cod+des)    14279 non-null  object
 19  Diag 20 Secundario (cod+des)    14279 non-null  object
 20  Diag 21 Secundario (cod+des)    14279 non-null  object
 21  Diag 22 Secundario (cod+des)    14279 non-null  object
 22  Diag 23 Secundario (cod+des)    14279 non-null  object
 23  Diag 24 Secundario (cod+des)    14279 non-null  object
 24  Diag 25 Secundario (cod+des)    14279 non-null  object
 25  Diag 26 Secundario (cod+des)    14279 non-null  object
 26  Diag 27 Secundario (cod+des)    14279 non-null  object
 27  Diag 28 Secundario (cod+des)    14279 non-null  object
 28  Diag 29 Secundario (cod+des)    14279 non-null  object
 29  Diag 30 Secundario (cod+des)    14279 non-null  object
 30  Diag 31 Secundario (cod+des)    14279 non-null  object
 31  Diag 32 Secundario (cod+des)    14279 non-null  object
 32  Diag 33 Secundario (cod+des)    14279 non-null  object
 33  Diag 34 Secundario (cod+des)    14279 non-null  object
 34  Diag 35 Secundario (cod+des)    14279 non-null  object
 35  Proced 01 Principal (cod+des)   14279 non-null  float64
 36  Proced 02 Secundario (cod+des)  14279 non-null  float64
 37  Proced 03 Secundario (cod+des)  14279 non-null  float64
 38  Proced 04 Secundario (cod+des)  14279 non-null  float64
 39  Proced 05 Secundario (cod+des)  14279 non-null  float64
 40  Proced 06 Secundario (cod+des)  14279 non-null  float64
 41  Proced 07 Secundario (cod+des)  14279 non-null  float64
 42  Proced 08 Secundario (cod+des)  14279 non-null  float64
 43  Proced 09 Secundario (cod+des)  14279 non-null  float64
 44  Proced 10 Secundario (cod+des)  14279 non-null  float64
 45  Proced 11 Secundario (cod+des)  14279 non-null  float64
 46  Proced 12 Secundario (cod+des)  14279 non-null  float64
 47  Proced 13 Secundario (cod+des)  14279 non-null  float64
 48  Proced 14 Secundario (cod+des)  14279 non-null  float64
 49  Proced 15 Secundario (cod+des)  14279 non-null  float64
 50  Proced 16 Secundario (cod+des)  14279 non-null  float64
 51  Proced 17 Secundario (cod+des)  14279 non-null  float64
 52  Proced 18 Secundario (cod+des)  14279 non-null  float64
 53  Proced 19 Secundario (cod+des)  14279 non-null  float64
 54  Proced 20 Secundario (cod+des)  14279 non-null  float64
 55  Proced 21 Secundario (cod+des)  14279 non-null  float64
 56  Proced 22 Secundario (cod+des)  14279 non-null  float64
 57  Proced 23 Secundario (cod+des)  14279 non-null  float64
 58  Proced 24 Secundario (cod+des)  14279 non-null  float64
 59  Proced 25 Secundario (cod+des)  14279 non-null  float64
 60  Proced 26 Secundario (cod+des)  14279 non-null  float64
 61  Proced 27 Secundario (cod+des)  14279 non-null  float64
 62  Proced 28 Secundario (cod+des)  14279 non-null  float64
 63  Proced 29 Secundario (cod+des)  14279 non-null  float64
 64  Proced 30 Secundario (cod+des)  14279 non-null  float64
 65  Edad en años                    14279 non-null  int64
 66  Sexo (Desc)                     14279 non-null  int64
 67  GRD                             14279 non-null  int64
dtypes: float64(30), int64(3), object(35)
memory usage: 7.4+ MB

Estadísticas descriptivas:

,Proced 01 Principal (cod+des),Proced 02 Secundario (cod+des),Proced 03 Secundario (cod+des),Proced 04 Secundario (cod+des),Proced 05 Secundario (cod+des),Proced 06 Secundario (cod+des),Proced 07 Secundario (cod+des),Proced 08 Secundario (cod+des),Proced 09 Secundario (cod+des),Proced 10 Secundario (cod+des),...,Proced 24 Secundario (cod+des),Proced 25 Secundario (cod+des),Proced 26 Secundario (cod+des),Proced 27 Secundario (cod+des),Proced 28 Secundario (cod+des),Proced 29 Secundario (cod+des),Proced 30 Secundario (cod+des),Edad en años,Sexo (Desc),GRD
count,14279.000000,14279.000000,14279.000000,14279.000000,14279.000000,14279.000000,14279.000000,14279.000000,14279.000000,14279.000000,...,14279.000000,14279.000000,14279.000000,14279.000000,14279.000000,14279.000000,14279.000000,14279.000000,14279.000000,14279.000000
mean,77.329146,81.019272,79.204390,80.902468,83.896197,81.468569,78.220332,72.865540,66.767705,60.018657,...,11.499991,10.407314,9.573633,8.674873,7.971287,7.289782,6.549803,39.238952,0.335878,10198.861685
std,16.321356,20.886600,28.720022,28.857812,26.315667,29.810508,34.124752,38.542663,41.841963,44.421579,...,30.471354,29.220067,28.160883,26.942494,25.934290,24.926749,23.722535,24.659801,0.472313,5041.461145
min,0.140000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1413.000000
25%,73.590000,75.690000,87.410000,88.190000,89.130000,89.260000,89.130000,73.090000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,23.000000,0.000000,6110.000000
50%,87.030000,88.430000,89.700000,90.390000,90.590000,90.590000,90.590000,90.590000,90.390000,89.700000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,36.000000,0.000000,10410.000000
75%,88.430000,90.390000,91.390000,96.590000,99.180000,99.180000,99.180000,99.180000,96.590000,93.960000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,60.000000,1.000000,14610.000000
max,99.980000,99.990000,99.840000,99.980000,99.840000,99.980000,99.980000,99.840000,99.840000,99.840000,...,99.840000,99.840000,99.840000,99.840000,99.840000,99.840000,99.840000,121.000000,1.000000,22412.000000

Label encoding

In [5]:
# Hacer una copia del DataFrame original
df_encoded = df.copy()

# Lista de columnas a procesar (excluyendo género que ya está en binario)
# Obtener todas las columnas excepto 'Sexo (Desc)'
columns_to_encode = [col for col in df.columns if col != 'Sexo (Desc)']

In [6]:
# Aplicar Label Encoding a las columnas de diagnóstico y procedimiento
print("Aplicando Label Encoding...")
label_encoders = {}
for column in columns_to_encode:
    if df[column].dtype == 'object':  # Solo aplicar a columnas categóricas
        le = LabelEncoder()
        # Manejar valores NaN reemplazándolos con una cadena especial
        df_encoded[column] = df_encoded[column].fillna('NA')
        df_encoded[column] = le.fit_transform(df_encoded[column].astype(str))
        label_encoders[column] = le

# Mostrar las primeras filas del DataFrame con Label Encoding
df_encoded.head()

Aplicando Label Encoding...

,Diag 01 Principal (cod+des),Diag 02 Secundario (cod+des),Diag 03 Secundario (cod+des),Diag 04 Secundario (cod+des),Diag 05 Secundario (cod+des),Diag 06 Secundario (cod+des),Diag 07 Secundario (cod+des),Diag 08 Secundario (cod+des),Diag 09 Secundario (cod+des),Diag 10 Secundario (cod+des),...,Proced 24 Secundario (cod+des),Proced 25 Secundario (cod+des),Proced 26 Secundario (cod+des),Proced 27 Secundario (cod+des),Proced 28 Secundario (cod+des),Proced 29 Secundario (cod+des),Proced 30 Secundario (cod+des),Edad en años,Sexo (Desc),GRD
0,24,41,373,638,38,462,391,26,6,242,...,99.84,88.72,90.42,90.52,91.39,91.33,87.03,40,1,18410
1,1364,508,1016,889,796,833,693,297,260,244,...,91.62,90.43,91.39,90.52,91.32,96.59,90.99,53,1,4101
2,575,1177,1051,452,975,330,649,23,31,9,...,99.84,91.73,90.53,99.26,89.39,89.66,89.65,65,1,4101
3,622,670,711,120,169,149,321,411,251,411,...,57.94,0.13,0.17,99.04,99.18,99.21,99.23,61,1,4102
4,1342,1571,1102,964,923,362,297,574,491,349,...,90.52,91.39,91.32,93.90,99.15,96.59,45.13,30,1,4102

In [8]:
# Guardar el DataFrame con Label Encoding
print("Guardando versión con Label Encoding...")
df_encoded.to_csv('label_encoded_data.csv', index=False)

Guardando versión con Label Encoding...

Onehot encoding

In [9]:
# Aplicar One-Hot Encoding
print("Aplicando One-Hot Encoding...")
# Crear un nuevo DataFrame para One-Hot Encoding
df_onehot = df.copy()

# Aplicar One-Hot Encoding a todas las columnas categóricas excepto género
for column in columns_to_encode:
    if df[column].dtype == 'object':  # Solo aplicar a columnas categóricas
        # Manejar valores NaN
        df_onehot[column] = df_onehot[column].fillna('NA')
        # Aplicar get_dummies
        dummies = pd.get_dummies(df_onehot[column], prefix=column)
        # Añadir las nuevas columnas al DataFrame
        df_onehot = pd.concat([df_onehot, dummies], axis=1)
        # Eliminar la columna original
        df_onehot.drop(column, axis=1, inplace=True)

# Mostrar las primeras filas del DataFrame con One-Hot Encoding
# Debido a que puede haber muchas columnas, mostramos solo las primeras 5 columnas
df_onehot.iloc[:, :5].head()

Aplicando One-Hot Encoding...

,Proced 01 Principal (cod+des),Proced 02 Secundario (cod+des),Proced 03 Secundario (cod+des),Proced 04 Secundario (cod+des),Proced 05 Secundario (cod+des)
0,86.28,34.91,88.38,87.41,88.75
1,31.10,86.28,96.72,93.90,89.70
2,86.22,54.59,96.72,31.10,45.13
3,54.19,39.98,86.28,54.62,96.72
4,54.11,45.90,46.73,46.20,86.28

In [10]:
# Guardar el DataFrame con One-Hot Encoding
print("Guardando versión con One-Hot Encoding...")
df_onehot.to_csv('onehot_encoded_data.csv', index=False)

Guardando versión con One-Hot Encoding...

Resumen

In [11]:
print("\nEstadísticas del proceso:")
print(f"Número de columnas en el dataset original: {len(df.columns)}")
print(f"Número de columnas después de Label Encoding: {len(df_encoded.columns)}")
print(f"Número de columnas después de One-Hot Encoding: {len(df_onehot.columns)}")
print("\n¡Proceso completado!")

Estadísticas del proceso:
Número de columnas en el dataset original: 68
Número de columnas después de Label Encoding: 68
Número de columnas después de One-Hot Encoding: 15583

¡Proceso completado!