__By:__ Victor Camero, Daniela Lavanderos

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import  svm
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.preprocessing import StandardScaler
from tabulate import tabulate
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_curve, roc_auc_score

# Lectura de los dataset y procesamiento

In [2]:
data_train = pd.read_csv('../data/dataModelCSV/train_data.csv', sep=';')
data_train.head()

,Diag 01 Principal (cod+des),Diag 02 Secundario (cod+des),Diag 03 Secundario (cod+des),Diag 04 Secundario (cod+des),Diag 05 Secundario (cod+des),Diag 06 Secundario (cod+des),Diag 07 Secundario (cod+des),Diag 08 Secundario (cod+des),Diag 09 Secundario (cod+des),Diag 10 Secundario (cod+des),...,Proced 24 Secundario (cod+des),Proced 25 Secundario (cod+des),Proced 26 Secundario (cod+des),Proced 27 Secundario (cod+des),Proced 28 Secundario (cod+des),Proced 29 Secundario (cod+des),Proced 30 Secundario (cod+des),Edad en años,Sexo (Desc),GRD
0,24,41,373,638,38,462,391,26,6,242,...,112,19,40,40,41,39,13,40,1,135
1,1364,508,1016,889,796,833,693,297,260,244,...,57,42,53,40,39,73,39,53,1,14
2,575,1177,1051,452,975,330,649,23,31,9,...,112,54,44,99,22,26,26,65,1,14
3,622,670,711,120,169,149,321,411,251,411,...,18,1,3,90,90,82,86,61,1,15
4,1342,1571,1102,964,923,362,297,574,491,349,...,46,53,51,72,88,73,9,30,1,15

In [3]:
data_test = pd.read_csv('../data/dataModelCSV/test_data.csv', sep=';')
data_test.head()

,Diag 01 Principal (cod+des),Diag 02 Secundario (cod+des),Diag 03 Secundario (cod+des),Diag 04 Secundario (cod+des),Diag 05 Secundario (cod+des),Diag 06 Secundario (cod+des),Diag 07 Secundario (cod+des),Diag 08 Secundario (cod+des),Diag 09 Secundario (cod+des),Diag 10 Secundario (cod+des),...,Proced 24 Secundario (cod+des),Proced 25 Secundario (cod+des),Proced 26 Secundario (cod+des),Proced 27 Secundario (cod+des),Proced 28 Secundario (cod+des),Proced 29 Secundario (cod+des),Proced 30 Secundario (cod+des),Edad en años,Sexo (Desc),GRD
0,462,509,518,168,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,27
1,967,978,816,787,115,846,715,627,544,492,...,0,0,0,0,0,0,0,45,0,120
2,264,295,1041,917,402,164,162,136,628,0,...,0,0,0,0,0,0,0,21,0,140
3,947,999,813,708,681,108,712,625,543,491,...,0,0,0,0,0,0,0,26,0,119
4,825,906,887,170,1100,0,0,0,0,0,...,0,0,0,0,0,0,0,32,0,104

In [4]:
rows_train_data, columns_train_data = data_train.shape
print(f"Cantidad de filas:{rows_train_data} y columnas:{columns_train_data} en el dataset de train_data.csv")

Cantidad de filas:9994 y columnas:68 en el dataset de train_data.csv

In [5]:
rows_test_data, columns_test_data = data_test.shape
print(f"Canitdad de filas:{rows_test_data} y columnas:{columns_test_data} en el dataset de test_data.csv")

Canitdad de filas:4284 y columnas:68 en el dataset de test_data.csv

## Revisión de datos faltante

In [6]:
data_test.isnull().sum()

Diag 01 Principal (cod+des)       0
Diag 02 Secundario (cod+des)      0
Diag 03 Secundario (cod+des)      0
Diag 04 Secundario (cod+des)      0
Diag 05 Secundario (cod+des)      0
                                 ..
Proced 29 Secundario (cod+des)    0
Proced 30 Secundario (cod+des)    0
Edad en años                      0
Sexo (Desc)                       0
GRD                               0
Length: 68, dtype: int64

In [7]:
data_train.isnull().sum()

Diag 01 Principal (cod+des)       0
Diag 02 Secundario (cod+des)      0
Diag 03 Secundario (cod+des)      0
Diag 04 Secundario (cod+des)      0
Diag 05 Secundario (cod+des)      0
                                 ..
Proced 29 Secundario (cod+des)    0
Proced 30 Secundario (cod+des)    0
Edad en años                      0
Sexo (Desc)                       0
GRD                               0
Length: 68, dtype: int64

__Nota:__ Los datos del dataset estan en buen estado.

In [8]:
data_train.describe

<bound method NDFrame.describe of       Diag 01 Principal (cod+des)  Diag 02 Secundario (cod+des)  \
0                              24                            41
1                            1364                           508
2                             575                          1177
3                             622                           670
4                            1342                          1571
...                           ...                           ...
9989                          991                           205
9990                          946                           999
9991                         1309                          1497
9992                          825                             0
9993                          967                           934

      Diag 03 Secundario (cod+des)  Diag 04 Secundario (cod+des)  \
0                              373                           638
1                             1016                           889
2                             1051                           452
3                              711                           120
4                             1102                           964
...                            ...                           ...
9989                          1395                             0
9990                           788                           787
9991                           212                           235
9992                             0                             0
9993                          1363                          1160

      Diag 05 Secundario (cod+des)  Diag 06 Secundario (cod+des)  \
0                               38                           462
1                              796                           833
2                              975                           330
3                              169                           149
4                              923                           362
...                            ...                           ...
9989                             0                             0
9990                           148                           846
9991                           223                           937
9992                             0                             0
9993                          1003                           853

      Diag 07 Secundario (cod+des)  Diag 08 Secundario (cod+des)  \
0                              391                            26
1                              693                           297
2                              649                            23
3                              321                           411
4                              297                           574
...                            ...                           ...
9989                             0                             0
9990                           715                           627
9991                           763                             0
9992                             0                             0
9993                           720                             0

      Diag 09 Secundario (cod+des)  Diag 10 Secundario (cod+des)  ...  \
0                                6                           242  ...
1                              260                           244  ...
2                               31                             9  ...
3                              251                           411  ...
4                              491                           349  ...
...                            ...                           ...  ...
9989                             0                             0  ...
9990                           544                           492  ...
9991                             0                             0  ...
9992                             0                             0  ...
9993                             0                             0  ...

      Proced 24 Secundario (cod+des)  Proced 25 Secundario (cod+des)  \
0                                112                              19
1                                 57                              42
2                                112                              54
3                                 18                               1
4                                 46                              53
...                              ...                             ...
9989                               0                               0
9990                               0                               0
9991                               0                               0
9992                               0                               0
9993                               0                               0

      Proced 26 Secundario (cod+des)  Proced 27 Secundario (cod+des)  \
0                                 40                              40
1                                 53                              40
2                                 44                              99
3                                  3                              90
4                                 51                              72
...                              ...                             ...
9989                               0                               0
9990                               0                               0
9991                               0                               0
9992                               0                               0
9993                               0                               0

      Proced 28 Secundario (cod+des)  Proced 29 Secundario (cod+des)  \
0                                 41                              39
1                                 39                              73
2                                 22                              26
3                                 90                              82
4                                 88                              73
...                              ...                             ...
9989                               0                               0
9990                               0                               0
9991                               0                               0
9992                               0                               0
9993                               0                               0

      Proced 30 Secundario (cod+des)  Edad en años  Sexo (Desc)  GRD
0                                 13            40            1  135
1                                 39            53            1   14
2                                 26            65            1   14
3                                 86            61            1   15
4                                  9            30            1   15
...                              ...           ...          ...  ...
9989                               0            32            0  115
9990                               0            36            0  119
9991                               0            22            0  152
9992                               0            42            0  112
9993                               0            26            0  120

[9994 rows x 68 columns]>

In [9]:
data_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 68 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Diag 01 Principal (cod+des)     9994 non-null   int64
 1   Diag 02 Secundario (cod+des)    9994 non-null   int64
 2   Diag 03 Secundario (cod+des)    9994 non-null   int64
 3   Diag 04 Secundario (cod+des)    9994 non-null   int64
 4   Diag 05 Secundario (cod+des)    9994 non-null   int64
 5   Diag 06 Secundario (cod+des)    9994 non-null   int64
 6   Diag 07 Secundario (cod+des)    9994 non-null   int64
 7   Diag 08 Secundario (cod+des)    9994 non-null   int64
 8   Diag 09 Secundario (cod+des)    9994 non-null   int64
 9   Diag 10 Secundario (cod+des)    9994 non-null   int64
 10  Diag 11 Secundario (cod+des)    9994 non-null   int64
 11  Diag 12 Secundario (cod+des)    9994 non-null   int64
 12  Diag 13 Secundario (cod+des)    9994 non-null   int64
 13  Diag 14 Secundario (cod+des)    9994 non-null   int64
 14  Diag 15 Secundario (cod+des)    9994 non-null   int64
 15  Diag 16 Secundario (cod+des)    9994 non-null   int64
 16  Diag 17 Secundario (cod+des)    9994 non-null   int64
 17  Diag 18 Secundario (cod+des)    9994 non-null   int64
 18  Diag 19 Secundario (cod+des)    9994 non-null   int64
 19  Diag 20 Secundario (cod+des)    9994 non-null   int64
 20  Diag 21 Secundario (cod+des)    9994 non-null   int64
 21  Diag 22 Secundario (cod+des)    9994 non-null   int64
 22  Diag 23 Secundario (cod+des)    9994 non-null   int64
 23  Diag 24 Secundario (cod+des)    9994 non-null   int64
 24  Diag 25 Secundario (cod+des)    9994 non-null   int64
 25  Diag 26 Secundario (cod+des)    9994 non-null   int64
 26  Diag 27 Secundario (cod+des)    9994 non-null   int64
 27  Diag 28 Secundario (cod+des)    9994 non-null   int64
 28  Diag 29 Secundario (cod+des)    9994 non-null   int64
 29  Diag 30 Secundario (cod+des)    9994 non-null   int64
 30  Diag 31 Secundario (cod+des)    9994 non-null   int64
 31  Diag 32 Secundario (cod+des)    9994 non-null   int64
 32  Diag 33 Secundario (cod+des)    9994 non-null   int64
 33  Diag 34 Secundario (cod+des)    9994 non-null   int64
 34  Diag 35 Secundario (cod+des)    9994 non-null   int64
 35  Proced 01 Principal (cod+des)   9994 non-null   int64
 36  Proced 02 Secundario (cod+des)  9994 non-null   int64
 37  Proced 03 Secundario (cod+des)  9994 non-null   int64
 38  Proced 04 Secundario (cod+des)  9994 non-null   int64
 39  Proced 05 Secundario (cod+des)  9994 non-null   int64
 40  Proced 06 Secundario (cod+des)  9994 non-null   int64
 41  Proced 07 Secundario (cod+des)  9994 non-null   int64
 42  Proced 08 Secundario (cod+des)  9994 non-null   int64
 43  Proced 09 Secundario (cod+des)  9994 non-null   int64
 44  Proced 10 Secundario (cod+des)  9994 non-null   int64
 45  Proced 11 Secundario (cod+des)  9994 non-null   int64
 46  Proced 12 Secundario (cod+des)  9994 non-null   int64
 47  Proced 13 Secundario (cod+des)  9994 non-null   int64
 48  Proced 14 Secundario (cod+des)  9994 non-null   int64
 49  Proced 15 Secundario (cod+des)  9994 non-null   int64
 50  Proced 16 Secundario (cod+des)  9994 non-null   int64
 51  Proced 17 Secundario (cod+des)  9994 non-null   int64
 52  Proced 18 Secundario (cod+des)  9994 non-null   int64
 53  Proced 19 Secundario (cod+des)  9994 non-null   int64
 54  Proced 20 Secundario (cod+des)  9994 non-null   int64
 55  Proced 21 Secundario (cod+des)  9994 non-null   int64
 56  Proced 22 Secundario (cod+des)  9994 non-null   int64
 57  Proced 23 Secundario (cod+des)  9994 non-null   int64
 58  Proced 24 Secundario (cod+des)  9994 non-null   int64
 59  Proced 25 Secundario (cod+des)  9994 non-null   int64
 60  Proced 26 Secundario (cod+des)  9994 non-null   int64
 61  Proced 27 Secundario (cod+des)  9994 non-null   int64
 62  Proced 28 Secundario (cod+des)  9994 non-null   int64
 63  Proced 29 Secundario (cod+des)  9994 non-null   int64
 64  Proced 30 Secundario (cod+des)  9994 non-null   int64
 65  Edad en años                    9994 non-null   int64
 66  Sexo (Desc)                     9994 non-null   int64
 67  GRD                             9994 non-null   int64
dtypes: int64(68)
memory usage: 5.2 MB

# Objetivo y funciones para las metricas

In [10]:
def medir_modelos(real, predicho):
    accuracy = accuracy_score(real, predicho) * 100
    print(f"Accuracy: {accuracy:.2f}%")
    
    precision = precision_score(real, predicho, average='macro', zero_division=0) * 100
    print(f"Precision (macro): {precision:.2f}%")
    
    recall = recall_score(real, predicho, average='macro', zero_division=0) * 100
    print(f"Recall (macro): {recall:.2f}%")

In [11]:
data_train.GRD = data_train.GRD.astype('category')
data_test.GRD = data_test.GRD.astype('category')

In [12]:
global_target = data_train["GRD"]
global_target_test = data_test["GRD"]

In [13]:
columns_name = data_train.columns.tolist()
columns_name.remove("GRD")
columns_name[0:4]

['Diag 01 Principal (cod+des)',
 'Diag 02 Secundario (cod+des)',
 'Diag 03 Secundario (cod+des)',
 'Diag 04 Secundario (cod+des)']

# Entrenamiento de Modelos

## Parametros para los modelos

In [14]:
modelos = [["Diag 01 Principal (cod+des)", "Diag 02 Secundario (cod+des)", "Proced 01 Principal (cod+des)", "Proced 03 Secundario (cod+des)", "Proced 04 Secundario (cod+des)", "Proced 05 Secundario (cod+des)", "Edad en años", "Sexo (Desc)"], # Modelo 1
           ["Diag 01 Principal (cod+des)", "Diag 02 Secundario (cod+des)", "Proced 01 Principal (cod+des)", "Proced 03 Secundario (cod+des)", "Proced 04 Secundario (cod+des)", "Proced 05 Secundario (cod+des)", "Edad en años"], # Modelo 2
           ["Diag 01 Principal (cod+des)", "Diag 02 Secundario (cod+des)", "Proced 01 Principal (cod+des)", "Proced 03 Secundario (cod+des)", "Proced 04 Secundario (cod+des)", "Proced 05 Secundario (cod+des)", "Sexo (Desc)"] 
          ]

In [15]:
modelos.append(columns_name)

## Modelo 1

In [16]:
inputs_modelo1 = np.asanyarray(data_train[modelos[0]])
test_input_model1 = np.asanyarray(data_test[modelos[0]])

In [17]:
scaler1 = StandardScaler().fit(inputs_modelo1)
x_train1 = scaler1.transform(inputs_modelo1)
x_test1 = scaler1.transform(test_input_model1)

### Modelo RBF

In [18]:
modelo_rbf1 = svm.SVC(kernel='rbf')
modelo_rbf1.fit(x_train1, global_target)

SVC()

In [19]:
svm_prediction_rbf1 = modelo_rbf1.predict(x_test1)
print(svm_prediction_rbf1)

[ 24 117 139 ...   6  62  15]

In [20]:
medir_modelos(global_target_test, svm_prediction_rbf1)

Accuracy: 47.46%
Precision (macro): 13.75%
Recall (macro): 15.73%

### Modelo sigmoid

In [21]:
modelo_sigmoid1 = svm.SVC(kernel='sigmoid')
modelo_sigmoid1.fit(x_train1, global_target)

SVC(kernel='sigmoid')

In [22]:
svm_prediction_sigmoid1 = modelo_sigmoid1.predict(x_test1)
print(svm_prediction_sigmoid1)

[ 24 117  61 ...  86  96  86]

In [23]:
medir_modelos(global_target_test, svm_prediction_sigmoid1)

Accuracy: 29.65%
Precision (macro): 8.78%
Recall (macro): 7.76%

## Modelo 2

In [24]:
inputs_modelo2 = np.asanyarray(data_train[modelos[1]])
test_input_model2 = np.asanyarray(data_test[modelos[1]])

In [25]:
scaler2 = StandardScaler().fit(inputs_modelo2)
x_train2 = scaler2.transform(inputs_modelo2)
x_test2 = scaler2.transform(test_input_model2)

### Modelo RBF

In [26]:
modelo_rbf2 = svm.SVC(kernel='rbf')
modelo_rbf2.fit(x_train2, global_target)

SVC()

In [27]:
svm_prediction_rbf2 = modelo_rbf2.predict(x_test2)
print(svm_prediction_rbf2)

[ 24 117 139 ...   6  96  15]

In [28]:
medir_modelos(global_target_test, svm_prediction_rbf2)

Accuracy: 48.69%
Precision (macro): 13.09%
Recall (macro): 16.12%

### Modelo sigmoid

In [29]:
modelo_sigmoid2 = svm.SVC(kernel='sigmoid')
modelo_sigmoid2.fit(x_train2, global_target)

SVC(kernel='sigmoid')

In [30]:
svm_prediction_sigmoid2 = modelo_sigmoid2.predict(x_test2)
print(svm_prediction_sigmoid2)

[ 61 117  61 ...  86  96  86]

In [31]:
medir_modelos(global_target_test, svm_prediction_sigmoid2)

Accuracy: 25.02%
Precision (macro): 5.56%
Recall (macro): 6.16%

## Modelo 3

In [32]:
inputs_modelo3 = np.asanyarray(data_train[modelos[2]])
test_input_model3 = np.asanyarray(data_test[modelos[2]])

In [33]:
scaler3 = StandardScaler().fit(inputs_modelo3)
x_train3 = scaler3.transform(inputs_modelo3)
x_test3 = scaler3.transform(test_input_model3)

### Modelo RBF

In [34]:
modelo_rbf3 = svm.SVC(kernel='rbf')
modelo_rbf3.fit(x_train3, global_target)

SVC()

In [35]:
svm_prediction_rbf3 = modelo_rbf3.predict(x_test3)
print(svm_prediction_rbf3)

[ 22 117 139 ...  86  62  16]

In [36]:
medir_modelos(global_target_test, svm_prediction_rbf3)

Accuracy: 47.36%
Precision (macro): 12.53%
Recall (macro): 14.91%

### Modelo sigmoid

In [37]:
modelo_sigmoid3 = svm.SVC(kernel='sigmoid')
modelo_sigmoid3.fit(x_train3, global_target)

SVC(kernel='sigmoid')

In [38]:
svm_prediction_sigmoid3 = modelo_sigmoid3.predict(x_test3)
print(svm_prediction_sigmoid3)

[ 82 117  61 ...  86  96 128]

In [39]:
svm_prediction_sigmoid3 = modelo_sigmoid3.predict(x_test3)
print(svm_prediction_sigmoid3)

[ 82 117  61 ...  86  96 128]

In [40]:
medir_modelos(global_target_test, svm_prediction_sigmoid3)

Accuracy: 25.28%
Precision (macro): 5.87%
Recall (macro): 5.81%

## Modelo 4

In [41]:
inputs_modelo4 = np.asanyarray(data_train[modelos[3]])
test_input_model4 = np.asanyarray(data_test[modelos[3]])

In [42]:
scaler4 = StandardScaler().fit(inputs_modelo4)
x_train4 = scaler4.transform(inputs_modelo4)
x_test4 = scaler4.transform(test_input_model4)

### Modelo RBF

In [43]:
modelo_rbf4 = svm.SVC(kernel='rbf')
modelo_rbf4.fit(x_train4, global_target)

SVC()

In [44]:
svm_prediction_rbf4 = modelo_rbf4.predict(x_test4)
print(svm_prediction_rbf4)

[ 24 117  22 ...   6  62  15]

In [45]:
medir_modelos(global_target_test, svm_prediction_rbf4)

Accuracy: 43.98%
Precision (macro): 10.91%
Recall (macro): 11.37%

### Modelo Sigmoid

In [46]:
modelo_sigmoid4 = svm.SVC(kernel='sigmoid')
modelo_sigmoid4.fit(x_train4, global_target)

SVC(kernel='sigmoid')

In [47]:
svm_prediction_sigmoid4 = modelo_sigmoid4.predict(x_test4)
print(svm_prediction_sigmoid4)

[ 24 117  61 ...   6  62  15]

In [48]:
svm_prediction_sigmoid4 = modelo_sigmoid4.predict(x_test4)
print(svm_prediction_sigmoid4)

[ 24 117  61 ...   6  62  15]

In [49]:
medir_modelos(global_target_test, svm_prediction_sigmoid4)

Accuracy: 41.57%
Precision (macro): 10.55%
Recall (macro): 10.75%